<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\MonitoringTindakLanjut;

class MonitoringTindakLanjutSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'objek_pemeriksaan' => 'PT PLN NUSA DAYA 2024',
                'aoi_count' => 0,
                'rekomendasi_count' => 0,
                'tindak_lanjut_target' => 0,
                'tindak_lanjut_real' => 0,
                'sisa_target' => 0,
                'sisa_real' => 0,
                'bulan_jan_target' => 0, 'bulan_jan_real' => 0,
                'bulan_feb_target' => 0, 'bulan_feb_real' => 0,
                'bulan_mar_target' => 0, 'bulan_mar_real' => 0,
                'bulan_apr_target' => 0, 'bulan_apr_real' => 0,
                'bulan_mei_target' => 0, 'bulan_mei_real' => 0,
                'bulan_jun_target' => 0, 'bulan_jun_real' => 0,
                'bulan_jul_target' => 0, 'bulan_jul_real' => 0,
                'bulan_ags_target' => 0, 'bulan_ags_real' => 0,
                'bulan_sep_target' => 0, 'bulan_sep_real' => 0,
                'bulan_okt_target' => 0, 'bulan_okt_real' => 0,
                'is_category' => true,
                'is_total' => false,
            ],
            [
                'objek_pemeriksaan' => 'AUDITEE PT PCN',
                'aoi_count' => 5,
                'rekomendasi_count' => 9,
                'tindak_lanjut_target' => 9,
                'tindak_lanjut_real' => 9,
                'sisa_target' => 0,
                'sisa_real' => 0,
                'bulan_jan_target' => 1, 'bulan_jan_real' => 1,
                'bulan_feb_target' => 2, 'bulan_feb_real' => 2,
                'bulan_mar_target' => 6, 'bulan_mar_real' => 6,
                'bulan_apr_target' => 0, 'bulan_apr_real' => 0,
                'bulan_mei_target' => 0, 'bulan_mei_real' => 0,
                'bulan_jun_target' => 0, 'bulan_jun_real' => 0,
                'bulan_jul_target' => 0, 'bulan_jul_real' => 0,
                'bulan_ags_target' => 0, 'bulan_ags_real' => 0,
                'bulan_sep_target' => 0, 'bulan_sep_real' => 0,
                'bulan_okt_target' => 0, 'bulan_okt_real' => 0,
                'is_category' => true,
                'is_total' => false,
            ],
            [
                'objek_pemeriksaan' => 'PT PCN 2024 - 2025',
                'aoi_count' => 0,
                'rekomendasi_count' => 0,
                'tindak_lanjut_target' => 0,
                'tindak_lanjut_real' => 0,
                'sisa_target' => 0,
                'sisa_real' => 0,
                'bulan_jan_target' => 0, 'bulan_jan_real' => 0,
                'bulan_feb_target' => 0, 'bulan_feb_real' => 0,
                'bulan_mar_target' => 0, 'bulan_mar_real' => 0,
                'bulan_apr_target' => 0, 'bulan_apr_real' => 0,
                'bulan_mei_target' => 0, 'bulan_mei_real' => 0,
                'bulan_jun_target' => 0, 'bulan_jun_real' => 0,
                'bulan_jul_target' => 0, 'bulan_jul_real' => 0,
                'bulan_ags_target' => 0, 'bulan_ags_real' => 0,
                'bulan_sep_target' => 0, 'bulan_sep_real' => 0,
                'bulan_okt_target' => 0, 'bulan_okt_real' => 0,
                'is_category' => true,
                'is_total' => false,
            ],
            [
                'objek_pemeriksaan' => 'SITE MAKASSAR',
                'aoi_count' => 2,
                'rekomendasi_count' => 2,
                'tindak_lanjut_target' => 2,
                'tindak_lanjut_real' => 2,
                'sisa_target' => 0,
                'sisa_real' => 0,
                'bulan_jan_target' => 2, 'bulan_jan_real' => 2,
                'bulan_feb_target' => 0, 'bulan_feb_real' => 0,
                'bulan_mar_target' => 0, 'bulan_mar_real' => 0,
                'bulan_apr_target' => 0, 'bulan_apr_real' => 0,
                'bulan_mei_target' => 0, 'bulan_mei_real' => 0,
                'bulan_jun_target' => 0, 'bulan_jun_real' => 0,
                'bulan_jul_target' => 0, 'bulan_jul_real' => 0,
                'bulan_ags_target' => 0, 'bulan_ags_real' => 0,
                'bulan_sep_target' => 0, 'bulan_sep_real' => 0,
                'bulan_okt_target' => 0, 'bulan_okt_real' => 0,
                'is_category' => false,
                'is_total' => false,
            ],
            [
                'objek_pemeriksaan' => 'SPIN KANTOR PUSAT',
                'aoi_count' => 1,
                'rekomendasi_count' => 10,
                'tindak_lanjut_target' => 5,
                'tindak_lanjut_real' => 5,
                'sisa_target' => 5,
                'sisa_real' => 0,
                'bulan_jan_target' => 0, 'bulan_jan_real' => 0,
                'bulan_feb_target' => 0, 'bulan_feb_real' => 0,
                'bulan_mar_target' => 3, 'bulan_mar_real' => 3,
                'bulan_apr_target' => 2, 'bulan_apr_real' => 2,
                'bulan_mei_target' => 1, 'bulan_mei_real' => 0,
                'bulan_jun_target' => 3, 'bulan_jun_real' => 0,
                'bulan_jul_target' => 1, 'bulan_jul_real' => 0,
                'bulan_ags_target' => 0, 'bulan_ags_real' => 0,
                'bulan_sep_target' => 0, 'bulan_sep_real' => 0,
                'bulan_okt_target' => 0, 'bulan_okt_real' => 0,
                'is_category' => false,
                'is_total' => false,
            ],
            [
                'objek_pemeriksaan' => 'DIVISI RENUS',
                'aoi_count' => 1,
                'rekomendasi_count' => 3,
                'tindak_lanjut_target' => 0,
                'tindak_lanjut_real' => 0,
                'sisa_target' => 3,
                'sisa_real' => 0,
                'bulan_jan_target' => 0, 'bulan_jan_real' => 0,
                'bulan_feb_target' => 0, 'bulan_feb_real' => 0,
                'bulan_mar_target' => 0, 'bulan_mar_real' => 0,
                'bulan_apr_target' => 0, 'bulan_apr_real' => 0,
                'bulan_mei_target' => 0, 'bulan_mei_real' => 0,
                'bulan_jun_target' => 3, 'bulan_jun_real' => 0,
                'bulan_jul_target' => 0, 'bulan_jul_real' => 0,
                'bulan_ags_target' => 0, 'bulan_ags_real' => 0,
                'bulan_sep_target' => 0, 'bulan_sep_real' => 0,
                'bulan_okt_target' => 0, 'bulan_okt_real' => 0,
                'is_category' => false,
                'is_total' => false,
            ],
            [
                'objek_pemeriksaan' => 'CABANG KALSELTENG',
                'aoi_count' => 2,
                'rekomendasi_count' => 5,
                'tindak_lanjut_target' => 2,
                'tindak_lanjut_real' => 1,
                'sisa_target' => 4,
                'sisa_real' => 0,
                'bulan_jan_target' => 0, 'bulan_jan_real' => 0,
                'bulan_feb_target' => 0, 'bulan_feb_real' => 0,
                'bulan_mar_target' => 0, 'bulan_mar_real' => 0,
                'bulan_apr_target' => 2, 'bulan_apr_real' => 1,
                'bulan_mei_target' => 0, 'bulan_mei_real' => 0,
                'bulan_jun_target' => 2, 'bulan_jun_real' => 0,
                'bulan_jul_target' => 0, 'bulan_jul_real' => 0,
                'bulan_ags_target' => 0, 'bulan_ags_real' => 0,
                'bulan_sep_target' => 1, 'bulan_sep_real' => 0,
                'bulan_okt_target' => 0, 'bulan_okt_real' => 0,
                'is_category' => false,
                'is_total' => false,
            ],
            [
                'objek_pemeriksaan' => 'JUMLAH',
                'aoi_count' => 11,
                'rekomendasi_count' => 29,
                'tindak_lanjut_target' => 18,
                'tindak_lanjut_real' => 17,
                'sisa_target' => 12,
                'sisa_real' => 0,
                'bulan_jan_target' => 3, 'bulan_jan_real' => 3,
                'bulan_feb_target' => 2, 'bulan_feb_real' => 2,
                'bulan_mar_target' => 9, 'bulan_mar_real' => 9,
                'bulan_apr_target' => 4, 'bulan_apr_real' => 3,
                'bulan_mei_target' => 1, 'bulan_mei_real' => 0,
                'bulan_jun_target' => 8, 'bulan_jun_real' => 0,
                'bulan_jul_target' => 0, 'bulan_jul_real' => 1,
                'bulan_ags_target' => 0, 'bulan_ags_real' => 0,
                'bulan_sep_target' => 1, 'bulan_sep_real' => 0,
                'bulan_okt_target' => 0, 'bulan_okt_real' => 0,
                'is_category' => false,
                'is_total' => true,
            ],
        ];

        foreach ($data as $item) {
            MonitoringTindakLanjut::create($item);
        }
    }
}
