<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class PelaporanTemuanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pelaporan_temuan')->insert([
            [
                'nomor_urut_iss' => 1,
                'pelaporan_hasil_audit_id' => 1,
                'hasil_temuan' => 'Dokumentasi transaksi keuangan tidak lengkap dan tidak sesuai dengan standar akuntansi yang berlaku. Beberapa transaksi tidak memiliki bukti pendukung yang memadai.',
                'kode_aoi_id' => 1,
                'kode_risk_id' => 1,
                'nomor_iss' => 'ISS.001/PO PCN/SPI.01.02/01/01/2024',
                'tahun' => 2024,
                'permasalahan' => 'Kurangnya pemahaman karyawan terhadap SOP yang berlaku.',
                'penyebab' => 'Kurangnya pemahaman karyawan terhadap SOP yang berlaku. Proses workflow yang tidak terstruktur dengan baik. Kebijakan yang belum jelas dan tidak terkomunikasikan dengan baik. Sistem informasi yang belum terintegrasi dengan optimal. Perubahan regulasi yang belum diadaptasi dengan cepat.',
                'kriteria' => 'Sesuai dengan standar pengendalian internal yang berlaku.',
                'dampak_terjadi' => 'Terjadi kesalahan dalam pencatatan transaksi keuangan.',
                'dampak_potensi' => 'Potensi kerugian finansial dan reputasi perusahaan.',
                'signifikan' => 'Tinggi',
                'status_approval' => 'approved',
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nomor_urut_iss' => 2,
                'pelaporan_hasil_audit_id' => 1,
                'hasil_temuan' => 'Proses approval transaksi keuangan tidak dilakukan sesuai dengan hierarki yang telah ditetapkan. Beberapa transaksi dengan nilai besar tidak mendapat approval dari level manajemen yang sesuai.',
                'kode_aoi_id' => 2,
                'kode_risk_id' => 2,
                'nomor_iss' => 'ISS.001/PO PCN/SPI.01.02/01/02/2024',
                'tahun' => 2024,
                'permasalahan' => 'Proses approval transaksi keuangan tidak sesuai hierarki.',
                'penyebab' => 'Kurangnya pemahaman terhadap kebijakan approval. Proses workflow approval yang tidak terstruktur. Kebijakan approval yang belum jelas. Sistem approval yang belum otomatis. Perubahan regulasi approval yang belum diimplementasi.',
                'kriteria' => 'Sesuai dengan standar pengendalian internal yang berlaku.',
                'dampak_terjadi' => 'Transaksi besar tidak mendapat approval yang sesuai.',
                'dampak_potensi' => 'Potensi fraud dan kerugian finansial.',
                'signifikan' => 'Tinggi',
                'status_approval' => 'approved',
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nomor_urut_iss' => 3,
                'pelaporan_hasil_audit_id' => 2,
                'hasil_temuan' => 'Sistem pengendalian risiko operasional belum terintegrasi dengan baik. Identifikasi dan penilaian risiko tidak dilakukan secara sistematis dan berkelanjutan.',
                'kode_aoi_id' => 3,
                'kode_risk_id' => 3,
                'nomor_iss' => 'ISS.002/PO PCN/SPI.01.03/01/01/2024',
                'tahun' => 2024,
                'permasalahan' => 'Sistem pengendalian risiko operasional belum optimal.',
                'penyebab' => 'Kurangnya kompetensi dalam manajemen risiko. Proses identifikasi risiko yang tidak sistematis. Kebijakan manajemen risiko yang belum komprehensif. Sistem monitoring risiko yang belum real-time. Dinamika lingkungan bisnis yang cepat berubah.',
                'kriteria' => 'Sesuai dengan framework manajemen risiko yang diakui.',
                'dampak_terjadi' => 'Beberapa risiko operasional tidak terdeteksi tepat waktu.',
                'dampak_potensi' => 'Potensi gangguan operasional dan kerugian bisnis.',
                'signifikan' => 'Medium',
                'status_approval' => 'pending',
                'approved_by' => null,
                'approved_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nomor_urut_iss' => 4,
                'pelaporan_hasil_audit_id' => 2,
                'hasil_temuan' => 'Monitoring dan pelaporan risiko tidak dilakukan secara real-time. Informasi risiko tidak tersedia secara tepat waktu untuk pengambilan keputusan manajemen.',
                'kode_aoi_id' => 4,
                'kode_risk_id' => 4,
                'nomor_iss' => 'ISS.002/PO PCN/SPI.01.03/01/02/2024',
                'tahun' => 2024,
                'permasalahan' => 'Monitoring dan pelaporan risiko tidak real-time.',
                'penyebab' => 'Kurangnya awareness terhadap pentingnya monitoring risiko. Proses monitoring yang tidak terstruktur. Kebijakan monitoring yang belum jelas. Sistem monitoring yang belum otomatis. Tekanan bisnis yang mengharuskan keputusan cepat.',
                'kriteria' => 'Sesuai dengan framework manajemen risiko yang diakui.',
                'dampak_terjadi' => 'Informasi risiko tidak tersedia tepat waktu.',
                'dampak_potensi' => 'Potensi keputusan yang tidak optimal.',
                'signifikan' => 'Medium',
                'status_approval' => 'pending',
                'approved_by' => null,
                'approved_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nomor_urut_iss' => 5,
                'pelaporan_hasil_audit_id' => 3,
                'hasil_temuan' => 'Kepatuhan terhadap regulasi sektor keuangan belum optimal. Beberapa ketentuan regulator tidak diimplementasikan dengan baik dalam proses bisnis.',
                'kode_aoi_id' => 5,
                'kode_risk_id' => 5,
                'nomor_iss' => 'ISS.003/PO PCN/SPI.01.04/01/01/2024',
                'tahun' => 2024,
                'permasalahan' => 'Kepatuhan terhadap regulasi sektor keuangan belum optimal.',
                'penyebab' => 'Kesadaran kepatuhan yang masih rendah di beberapa unit. Proses monitoring kepatuhan yang tidak terstruktur. Kebijakan kepatuhan yang belum terintegrasi dengan baik. Sistem pelaporan kepatuhan yang belum otomatis. Perubahan regulasi yang sering terjadi.',
                'kriteria' => 'Sesuai dengan standar kepatuhan yang berlaku.',
                'dampak_terjadi' => 'Beberapa pelanggaran regulasi tidak terdeteksi.',
                'dampak_potensi' => 'Potensi sanksi regulator dan kerugian reputasi.',
                'signifikan' => 'Tinggi',
                'status_approval' => 'approved',
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nomor_urut_iss' => 6,
                'pelaporan_hasil_audit_id' => 3,
                'hasil_temuan' => 'Sistem pelaporan kepatuhan tidak terintegrasi dan tidak menyediakan informasi yang komprehensif. Pelaporan kepada regulator sering terlambat dan tidak akurat.',
                'kode_aoi_id' => 1,
                'kode_risk_id' => 1,
                'nomor_iss' => 'ISS.003/PO PCN/SPI.01.04/01/02/2024',
                'tahun' => 2024,
                'permasalahan' => 'Sistem pelaporan kepatuhan tidak terintegrasi.',
                'penyebab' => 'Kurangnya koordinasi antar unit dalam pelaporan. Proses pelaporan yang tidak terstruktur. Kebijakan pelaporan yang belum jelas. Sistem pelaporan yang belum otomatis. Deadline regulator yang ketat.',
                'kriteria' => 'Sesuai dengan standar kepatuhan yang berlaku.',
                'dampak_terjadi' => 'Pelaporan kepada regulator terlambat dan tidak akurat.',
                'dampak_potensi' => 'Potensi sanksi regulator dan kerugian reputasi.',
                'signifikan' => 'Tinggi',
                'status_approval' => 'approved',
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
} 