<!DOCTYPE html>
<html lang="en">
<head>
    @include('layouts.partials/title-meta', ['title' => $title])
    @yield('css')
    @include('layouts.partials/head-css')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Select2 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        /* ===== DATA TABLES PREMIUM CUSTOM STYLE ===== */
        .dataTables_wrapper {
            padding-top: 0 !important;
            padding-bottom: 0 !important;
        }
        /* Header & Footer rows generated by Bootstrap DataTables */
        .dataTables_wrapper .row:first-child {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 16px 24px !important;
            background-color: #f8fafc;
            border-bottom: 1px solid #edf2f7;
            margin-left: 0 !important;
            margin-right: 0 !important;
            border-top-left-radius: 16px;
            border-top-right-radius: 16px;
        }
        .dataTables_wrapper .row:last-child {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 16px 24px !important;
            background-color: #f8fafc;
            border-top: 1px solid #edf2f7;
            margin-left: 0 !important;
            margin-right: 0 !important;
            border-bottom-left-radius: 16px;
            border-bottom-right-radius: 16px;
        }
        /* Reset default column padding classes inside these custom rows */
        .dataTables_wrapper .row:first-child > div,
        .dataTables_wrapper .row:last-child > div {
            padding-left: 0 !important;
            padding-right: 0 !important;
            width: auto !important;
            flex: 0 0 auto !important;
            max-width: 100% !important;
        }
        /* Length select input styling */
        .dataTables_length label {
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 0.82rem;
            font-weight: 600;
            color: #64748b;
            margin-bottom: 0 !important;
        }
        .dataTables_length select {
            padding: 0.4rem 2rem 0.4rem 0.8rem !important;
            font-size: 0.82rem !important;
            font-weight: 600 !important;
            color: #1e293b !important;
            border: 1px solid #cbd5e1 !important;
            border-radius: 8px !important;
            background-color: #fff !important;
            cursor: pointer;
            outline: none;
            box-shadow: none !important;
        }
        .dataTables_length select:focus {
            border-color: #2d6a9f !important;
        }
        /* Search bar input styling */
        .dataTables_filter label {
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 0.82rem;
            font-weight: 600;
            color: #64748b;
            margin-bottom: 0 !important;
        }
        .dataTables_filter input {
            padding: 0.4rem 0.8rem !important;
            font-size: 0.82rem !important;
            border: 1px solid #cbd5e1 !important;
            border-radius: 8px !important;
            outline: none;
            width: 200px !important;
            transition: all 0.2s ease-in-out;
            background-color: #fff !important;
        }
        .dataTables_filter input:focus {
            border-color: #2d6a9f !important;
            box-shadow: 0 0 0 3px rgba(45, 106, 159, 0.15) !important;
            width: 240px !important;
        }
        /* Information label styling */
        .dataTables_info {
            font-size: 0.82rem !important;
            font-weight: 600 !important;
            color: #64748b !important;
            padding-top: 0 !important;
        }
        /* Pagination styling */
        .dataTables_paginate {
            padding-top: 0 !important;
        }
        .dataTables_paginate .pagination {
            margin: 0 !important;
            gap: 4px;
        }
        .dataTables_paginate .page-item .page-link {
            padding: 6px 12px !important;
            font-size: 0.82rem !important;
            font-weight: 600 !important;
            color: #64748b !important;
            background-color: #fff !important;
            border: 1px solid #e2e8f0 !important;
            border-radius: 6px !important;
            transition: all 0.2s;
        }
        .dataTables_paginate .page-item.active .page-link {
            color: #fff !important;
            background-color: #1a3a5c !important;
            border-color: #1a3a5c !important;
        }
        .dataTables_paginate .page-item:not(.active):hover .page-link {
            background-color: #f1f5f9 !important;
            color: #1e293b !important;
        }

        .select2-container .select2-selection--single {
            height: 38px !important;
            border: 1px solid #dee2e6;
            border-radius: 0.25rem;
            display: flex;
            align-items: center;
        }
        .select2-container--default .select2-selection--single .select2-selection__arrow {
            height: 36px !important;
            right: 5px;
        }
        .select2-container--default .select2-selection--single .select2-selection__rendered {
            color: #495057;
            padding-left: 12px;
            line-height: 36px;
        }
        .input-group > .select2-container--default {
            width: auto !important;
            flex: 1 1 auto;
        }
        .select2-container--default .select2-results__option--highlighted[aria-selected] {
            background-color: #3e63d2;
            color: white;
        }
    </style>
</head>

<body data-menu-color="light" data-sidebar="default" @yield('body') >

<div id="app-layout">

    @include('layouts.partials/topbar')
    @include('layouts.partials/sidebar')

    <div class="content-page">
        <div class="content">
            <div class="container-xxl">
                @if(session('success'))
                    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                    <script>
                        Swal.fire({
                            icon: 'success',
                            title: 'Berhasil!',
                            text: '{{ session('success') }}',
                            showConfirmButton: false,
                            timer: 3000
                        });
                    </script>
                @endif

                @if(session('error'))
                    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                    <script>
                        Swal.fire({
                            icon: 'error',
                            title: 'Terjadi Kesalahan!',
                            text: '{{ session('error') }}',
                            confirmButtonColor: '#1a3a5c',
                            confirmButtonText: 'Tutup'
                        });
                    </script>
                @endif

                @if($errors->any() && !($errors->has('old_password') || $errors->has('password')))
                    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                    <script>
                        Swal.fire({
                            icon: 'error',
                            title: 'Gagal Validasi!',
                            html: `<div class="text-start">
                                <ul class="mb-0">
                                    @foreach($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>`,
                            confirmButtonColor: '#1a3a5c',
                            confirmButtonText: 'Tutup'
                        });
                    </script>
                @endif
                
                @if(session('login_success'))
                    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11" 
                            onerror="this.onerror=null; this.src='https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.1/sweetalert2.all.min.js'">
                    </script>
                    <script>
                        document.addEventListener('DOMContentLoaded', function() {
                            // Check if Swal is loaded
                            if (typeof Swal === 'undefined') {
                                console.error('SweetAlert2 is not loaded!');
                                // Fallback: show simple alert
                                alert('Selamat Datang!\n\n{{ session('login_success')['name'] }}\nRole: {{ session('login_success')['role'] }}\nLogin pada: {{ session('login_success')['time'] }}');
                                return;
                            }
                            
                            let timerInterval;
                            Swal.fire({
                                icon: 'success',
                                title: '🎉 Selamat Datang!',
                                html: `
                                    <div style="text-align: center;">
                                        <p style="font-size: 1.1rem; margin: 10px 0;">
                                            <strong>{{ session('login_success')['name'] }}</strong>
                                        </p>
                                        <p style="color: #666; margin: 5px 0;">
                                            <i class="mdi mdi-shield-account"></i> 
                                            Role: <strong>{{ session('login_success')['role'] }}</strong>
                                        </p>
                                        <p style="color: #666; margin: 5px 0;">
                                            <i class="mdi mdi-clock-outline"></i> 
                                            Login pada: <strong>{{ session('login_success')['time'] }}</strong>
                                        </p>
                                        <hr style="margin: 15px 0; border-color: #e0e0e0;">
                                        <p style="color: #999; font-size: 0.9rem;">
                                            <i class="mdi mdi-information-outline"></i> 
                                            Popup akan tertutup otomatis dalam <strong><span id="timer"></span></strong> detik
                                        </p>
                                    </div>
                                `,
                                showConfirmButton: true,
                                confirmButtonText: '<i class="mdi mdi-check"></i> OK',
                                confirmButtonColor: '#3085d6',
                                allowOutsideClick: true,
                                allowEscapeKey: true,
                                timer: 5000,
                                timerProgressBar: true,
                                didOpen: () => {
                                    const timer = Swal.getHtmlContainer().querySelector('#timer');
                                    timerInterval = setInterval(() => {
                                        const timeLeft = Math.ceil(Swal.getTimerLeft() / 1000);
                                        timer.textContent = timeLeft;
                                    }, 100);
                                },
                                willClose: () => {
                                    clearInterval(timerInterval);
                                }
                            });
                        });
                    </script>
                @endif
                
                @yield('content')
            </div>
        </div>

        @include("layouts.partials/footer")

    </div>

</div>

@vite(['resources/js/app.js'])
@include("layouts.partials/vendor")

<!-- Select2 JS -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>

<!-- SweetAlert2 - loaded early so all scripts below can use Swal -->
<script src="{{ asset('js/sweetalert2.all.min.js') }}"></script>

@yield('script')

<!-- Session Timeout Handler (needs Swal, must be after sweetalert2) -->
<script src="{{ asset('js/session-timeout.js') }}"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const logoutLink = document.getElementById('logout-link');
        if (logoutLink) {
            logoutLink.addEventListener('click', function (e) {
                e.preventDefault();
                if (typeof Swal !== 'undefined') {
                    Swal.fire({
                        title: 'Konfirmasi Logout',
                        text: 'Apakah Anda yakin ingin keluar?',
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Ya, Logout!',
                        cancelButtonText: 'Batal'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            submitLogout();
                        }
                    });
                } else {
                    if (confirm('Apakah Anda yakin ingin keluar?')) {
                        submitLogout();
                    }
                }
            });
        }

        function submitLogout() {
            const form = document.createElement('form');
            form.method = 'POST';
            form.action = '{{ route('logout') }}';
            form.style.display = 'none';
            const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
            const csrfInput = document.createElement('input');
            csrfInput.setAttribute('type', 'hidden');
            csrfInput.setAttribute('name', '_token');
            csrfInput.setAttribute('value', csrfToken);
            form.appendChild(csrfInput);
            document.body.appendChild(form);
            form.submit();
        }

        // Global Reset Password Modal Trigger
        const resetPasswordNavLink = document.getElementById('reset-password-nav-link');
        if (resetPasswordNavLink) {
            resetPasswordNavLink.addEventListener('click', function (e) {
                e.preventDefault();
                // Clear fields
                document.getElementById('global_old_password').value = '';
                document.getElementById('global_new_password').value = '';
                document.getElementById('global_new_password_confirmation').value = '';
                
                // Reset types & eye icons
                document.getElementById('global_old_password').type = 'password';
                document.getElementById('global_new_password').type = 'password';
                document.getElementById('global_new_password_confirmation').type = 'password';
                document.getElementById('global_old_password-eye').className = 'mdi mdi-eye';
                document.getElementById('global_new_password-eye').className = 'mdi mdi-eye';
                document.getElementById('global_new_password_confirmation-eye').className = 'mdi mdi-eye';
                
                // Show modal
                const modal = new bootstrap.Modal(document.getElementById('globalResetPasswordModal'));
                modal.show();
            });
        }

        // Auto-open global modal if there are password validation errors (and we aren't on profile page)
        @if ($errors->has('old_password') || $errors->has('password'))
            if (window.location.pathname.indexOf('/utility/profile') === -1) {
                const modal = new bootstrap.Modal(document.getElementById('globalResetPasswordModal'));
                modal.show();
            }
        @endif
    });

    function toggleGlobalPasswordVisibility(id) {
        const input = document.getElementById(id);
        const eye = document.getElementById(id + '-eye');
        if (input.type === 'password') {
            input.type = 'text';
            eye.className = 'mdi mdi-eye-off';
        } else {
            input.type = 'password';
            eye.className = 'mdi mdi-eye';
        }
    }
</script>

@stack('scripts')

<script>
    window.addEventListener('load', function() {
        // Initialize Select2 on any select with class 'select2-search'
        if (typeof $.fn.select2 !== 'undefined') {
            $('.select2-search').select2({
                width: '100%'
            });
        }
    });
</script>

{{-- ===== GLOBAL MODAL RESET PASSWORD ===== --}}
<div class="modal fade" id="globalResetPasswordModal" tabindex="-1" aria-labelledby="globalResetPasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="border-radius: 16px; border: none; box-shadow: 0 10px 30px rgba(0,0,0,0.15);">
            <div class="modal-header border-bottom-0 pb-0" style="padding: 24px 24px 0;">
                <h5 class="modal-title fw-bold text-dark" id="globalResetPasswordModalLabel" style="font-size: 1.15rem; display: inline-flex; align-items: center; gap: 8px;">
                    <i class="mdi mdi-key-change text-primary" style="font-size: 1.4rem;"></i>
                    Reset / Ubah Password Anda
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="global-reset-password-form" method="POST" action="{{ route('profile.change-password') }}">
                @csrf
                <div class="modal-body" style="padding: 20px 24px;">
                    <p class="text-muted mb-3" style="font-size: 0.85rem;">
                        Silakan masukkan password lama Anda dan password baru yang ingin digunakan.
                    </p>
                    
                    <div class="mb-3">
                        <label for="global_old_password" class="form-label fw-semibold text-dark mb-1" style="font-size: 0.82rem;">Password Lama</label>
                        <div class="input-group">
                            <span class="input-group-text bg-light border-end-0" style="border-radius: 8px 0 0 8px;"><i class="mdi mdi-lock-outline"></i></span>
                            <input type="password" 
                                   name="old_password" 
                                   id="global_old_password" 
                                   class="form-control border-start-0 @error('old_password') is-invalid @enderror" 
                                   style="border-radius: 0 8px 8px 0; font-size: 0.875rem;" 
                                   placeholder="Masukkan password saat ini" 
                                   required>
                            <button class="btn btn-outline-secondary" type="button" onclick="toggleGlobalPasswordVisibility('global_old_password')" style="border-radius: 0 8px 8px 0;">
                                <i class="mdi mdi-eye" id="global_old_password-eye"></i>
                            </button>
                            @error('old_password')
                                <div class="invalid-feedback d-block">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="global_new_password" class="form-label fw-semibold text-dark mb-1" style="font-size: 0.82rem;">Password Baru</label>
                        <div class="input-group">
                            <span class="input-group-text bg-light border-end-0" style="border-radius: 8px 0 0 8px;"><i class="mdi mdi-lock-open-outline"></i></span>
                            <input type="password" 
                                   name="password" 
                                   id="global_new_password" 
                                   class="form-control border-start-0 @error('password') is-invalid @enderror" 
                                   style="border-radius: 0 8px 8px 0; font-size: 0.875rem;" 
                                   placeholder="Minimal 6 karakter" 
                                   required>
                            <button class="btn btn-outline-secondary" type="button" onclick="toggleGlobalPasswordVisibility('global_new_password')" style="border-radius: 0 8px 8px 0;">
                                <i class="mdi mdi-eye" id="global_new_password-eye"></i>
                            </button>
                            @error('password')
                                <div class="invalid-feedback d-block">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    
                    <div class="mb-0">
                        <label for="global_new_password_confirmation" class="form-label fw-semibold text-dark mb-1" style="font-size: 0.82rem;">Konfirmasi Password Baru</label>
                        <div class="input-group">
                            <span class="input-group-text bg-light border-end-0" style="border-radius: 8px 0 0 8px;"><i class="mdi mdi-lock-check-outline"></i></span>
                            <input type="password" 
                                   name="password_confirmation" 
                                   id="global_new_password_confirmation" 
                                   class="form-control border-start-0" 
                                   style="border-radius: 0 8px 8px 0; font-size: 0.875rem;" 
                                   placeholder="Ulangi password baru" 
                                   required>
                            <button class="btn btn-outline-secondary" type="button" onclick="toggleGlobalPasswordVisibility('global_new_password_confirmation')" style="border-radius: 0 8px 8px 0;">
                                <i class="mdi mdi-eye" id="global_new_password_confirmation-eye"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer border-top-0 pt-0" style="padding: 0 24px 24px;">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal" style="border-radius: 8px; font-weight: 600; font-size: 0.85rem; padding: 8px 16px;">Batal</button>
                    <button type="submit" class="btn btn-primary" style="border-radius: 8px; font-weight: 600; font-size: 0.85rem; padding: 8px 16px; background: #1a3a5c; border-color: #1a3a5c;">Simpan Password</button>
                </div>
            </form>
        </div>
    </div>
</div>
@auth
    @include('layouts.partials/reminders-popup')
@endauth

</body>
</html>
